name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: "🚀 Features"
    labels: ["feat", "feature, enhancement"]
  - title: "🐞 Fixes"
    labels: ["fix", "bug", "bugfix"]
  - title: "🧰 Maintenance"
    labels: ["chore", "refactor", "deps", "dependencies", "build", "ci"]
  - title: "📝 Docs"
    labels: ["docs"]

change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"
change-title-escapes: "\\<*_&"

exclude-labels:
  - "skip-changelog"
  - "wip"
  - "no-changelog"

template: |
  ## What’s Changed
  $CHANGES

version-resolver:
  major:
    labels: ["semver:major", "major"]
  minor:
    labels: ["semver:minor", "minor", "feat"]
  patch:
    labels: ["semver:patch", "patch", "fix", "chore", "ci", "docs"]
  default: patch

autolabeler:
  - label: "feat"
    title:
      - "/^feat/i"
  - label: "fix"
    title:
      - "/^fix/i"
  - label: "chore"
    title:
      - "/^chore/i"
  - label: "docs"
    title:
      - "/^docs/i"
  - label: "ci"
    title:
      - "/^ci/i"
