```yaml
blank_issues_enabled: false
contact_links:
  - name: Questions / Help
    url: https://github.com/Cyber-preacher/humanode-chat/discussions
    about: Ask questions and get help in Discussions.
```
