name: CI
on:
  push:
    branches: [ main, dev, sync/dev-onto-main, "**" ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Use Node (from .nvmrc or fallback)
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          node-version: '20'
          cache: 'pnpm'

      - name: Install (workspace)
        run: pnpm -w install --frozen-lockfile=false

      - name: Prettier check
        run: pnpm -w run format:check

      # Only run the web tests (avoid Hardhat tests in CI for now)
      - name: Test (web)
        run: pnpm --filter web test -- --ci

      # Build web with safe dummy env (satisfies zod + Next build)
      - name: Build (web)
        env:
          NEXT_PUBLIC_SUPABASE_URL: https://example.supabase.co
          NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: sb_publishable_dummy_1234567890123456
        run: pnpm --filter web build
