name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1) Install pnpm first so setup-node's cache can find it
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      # 2) Then setup Node and enable pnpm cache
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      # 3) Install deps for all workspaces
      - name: Install deps (all workspaces)
        run: pnpm -r install --no-frozen-lockfile

      # 4) Compile and build
      - name: Compile contracts
        run: pnpm run compile

      - name: Build web
        working-directory: apps/web
        run: pnpm run build
