name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - run: pnpm -w install --frozen-lockfile

      # lint, test, build — adapt to your monorepo as needed
      - run: pnpm -w run format:check
      - run: pnpm -w run compile || true
      - run: pnpm --filter web test -- --ci --runInBand
      - run: pnpm --filter web build
