name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      # Install pnpm on the runner
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install deps (all workspaces)
        run: pnpm -r install --no-frozen-lockfile

      - name: Compile contracts
        run: pnpm run compile

      - name: Build web
        working-directory: apps/web
        run: pnpm run build
