name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # ⬇️ This is the key piece for B)
      - run: pnpm -w install --frozen-lockfile=false

      - run: pnpm -w run format:check

      # Optional: run tests/build
      - run: pnpm -r test --if-present
      - run: pnpm --filter web build
